apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: xxtechconfspeakers-api
  annotations:
    github.com/project-slug: andeemarks/xxtechconfspeakers-api
spec:
  type: openapi
  lifecycle: production
  owner: guests
